// Barrel file for presentational components, which will be used to compose our smart containers;
export { default as AllCampusesView } from "./AllCampusesView";
export { default as CampusView } from "./CampusView";
export { default as AddCampusFormView } from "./AddCampusFormView";
export { default as EditCampusFormView } from "./EditCampusFormView";
export {default as NavBarView} from "./NavBarView";
export { default as HomeView } from "./HomeView";
export { default as AllStudentsView } from "./AllStudentsView";
export { default as StudentView } from "./StudentView";
export { default as AddStudentFormView } from "./AddStudentFormView";
export { default as StudentNameListView } from "./StudentNameListView";
